version: 2.1
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Assemble release build
          command: |
            cd android && chmod +x gradlew && ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  version: 2
  build_and_test:
    jobs:
      - android
